<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Customer added sucessfullyCustomer-00000011613........Customer-00000011613]]>
    </line>
    <line>
      <![CDATA[Customer added sucessfullyCustomer-00000011614........Customer-00000011614]]>
    </line>
    <line>
      <![CDATA[Customer added sucessfullyCustomer-00000011615........Customer-00000011615]]>
    </line>
    <line>
      <![CDATA[Customer added sucessfullyCustomer-00000011616........Customer-00000011616]]>
    </line>
    <line>
      <![CDATA[Customer added sucessfullyCustomer-00000011617........Customer-00000011617]]>
    </line>
  </reporter-output>
  <suite started-at="2024-10-15T01:12:21 IST" name="Default suite" finished-at="2024-10-15T01:13:49 IST" duration-ms="88285">
    <groups>
    </groups>
    <test started-at="2024-10-15T01:12:21 IST" name="Default test" finished-at="2024-10-15T01:13:49 IST" duration-ms="88285">
      <class name="driverFactory.AppTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:driverFactory.AppTest@50eac852]" started-at="2024-10-15T01:12:21 IST" name="setUp" finished-at="2024-10-15T01:12:35 IST" duration-ms="14482" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="startTest()[pri:0, instance:driverFactory.AppTest@50eac852]" started-at="2024-10-15T01:12:35 IST" name="startTest" finished-at="2024-10-15T01:13:48 IST" duration-ms="72373" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "org.apache.poi.xssf.usermodel.XSSFCell.getCellType()" because the return value of "org.apache.poi.xssf.usermodel.XSSFRow.getCell(int)" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.poi.xssf.usermodel.XSSFCell.getCellType()" because the return value of "org.apache.poi.xssf.usermodel.XSSFRow.getCell(int)" is null
at utilities.ExcelFileUtil.getDataFromCell(ExcelFileUtil.java:35)
at driverFactory.AppTest.startTest(AppTest.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[Customer added sucessfullyCustomer-00000011613........Customer-00000011613]]>
            </line>
            <line>
              <![CDATA[Customer added sucessfullyCustomer-00000011614........Customer-00000011614]]>
            </line>
            <line>
              <![CDATA[Customer added sucessfullyCustomer-00000011615........Customer-00000011615]]>
            </line>
            <line>
              <![CDATA[Customer added sucessfullyCustomer-00000011616........Customer-00000011616]]>
            </line>
            <line>
              <![CDATA[Customer added sucessfullyCustomer-00000011617........Customer-00000011617]]>
            </line>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:driverFactory.AppTest@50eac852]" started-at="2024-10-15T01:13:48 IST" name="tearDown" finished-at="2024-10-15T01:13:49 IST" duration-ms="1360" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- driverFactory.AppTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
