<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="2" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[admin..master]]>
    </line>
    <line>
      <![CDATA[login sucessful]]>
    </line>
    <line>
      <![CDATA[admin..admin]]>
    </line>
    <line>
      <![CDATA[Incorrect user ID or password]]>
    </line>
    <line>
      <![CDATA[abc..xyz]]>
    </line>
    <line>
      <![CDATA[Incorrect user ID or password]]>
    </line>
    <line>
      <![CDATA[admin..master]]>
    </line>
    <line>
      <![CDATA[Customer added sucessfullyCustomer-00000011567........Customer-00000011567]]>
    </line>
    <line>
      <![CDATA[Customer added sucessfullyCustomer-00000011568........Customer-00000011568]]>
    </line>
    <line>
      <![CDATA[customer is not addedCustomer-00000011569.......Customer-00000007928]]>
    </line>
    <line>
      <![CDATA[Customer added sucessfullyCustomer-00000011570........Customer-00000011570]]>
    </line>
    <line>
      <![CDATA[Customer added sucessfullyCustomer-00000011571........Customer-00000011571]]>
    </line>
  </reporter-output>
  <suite started-at="2024-10-14T23:56:14 IST" name="Suite" finished-at="2024-10-14T23:59:00 IST" duration-ms="165576">
    <groups>
    </groups>
    <test started-at="2024-10-14T23:56:14 IST" name="login testcase" finished-at="2024-10-14T23:57:31 IST" duration-ms="77283">
      <class name="driverFactory.DriverScript">
        <test-method is-config="true" signature="setUp()[pri:0, instance:driverFactory.DriverScript@50eac852]" started-at="2024-10-14T23:56:14 IST" name="setUp" finished-at="2024-10-14T23:56:18 IST" duration-ms="3861" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="startTest()[pri:0, instance:driverFactory.DriverScript@50eac852]" started-at="2024-10-14T23:56:18 IST" name="startTest" finished-at="2024-10-14T23:57:31 IST" duration-ms="72707" status="FAIL">
          <exception class="org.openqa.selenium.NoSuchWindowException">
            <message>
              <![CDATA[no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=129.0.6668.100)
Build info: version: '4.18.0', revision: 'b6bf9de7cc'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.10'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [4a6b6e4d06e88e3b8bffa29be9d30ee9, getCurrentUrl {}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 129.0.6668.100, chrome: {chromedriverVersion: 129.0.6668.100 (cf58cba358d..., userDataDir: C:\Users\amare\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:51312}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:51312/devtoo..., se:cdpVersion: 129.0.6668.100, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 4a6b6e4d06e88e3b8bffa29be9d30ee9]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.NoSuchWindowException: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=129.0.6668.100)
Build info: version: '4.18.0', revision: 'b6bf9de7cc'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.10'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [4a6b6e4d06e88e3b8bffa29be9d30ee9, getCurrentUrl {}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 129.0.6668.100, chrome: {chromedriverVersion: 129.0.6668.100 (cf58cba358d..., userDataDir: C:\Users\amare\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:51312}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:51312/devtoo..., se:cdpVersion: 129.0.6668.100, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 4a6b6e4d06e88e3b8bffa29be9d30ee9
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:190)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:519)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:592)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:596)
at org.openqa.selenium.remote.RemoteWebDriver.getCurrentUrl(RemoteWebDriver.java:313)
at commonFunctions.FunctionLibrary.adminLogin(FunctionLibrary.java:25)
at driverFactory.DriverScript.startTest(DriverScript.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.NoSuchWindowException -->
          <reporter-output>
            <line>
              <![CDATA[admin..master]]>
            </line>
            <line>
              <![CDATA[login sucessful]]>
            </line>
            <line>
              <![CDATA[admin..admin]]>
            </line>
            <line>
              <![CDATA[Incorrect user ID or password]]>
            </line>
            <line>
              <![CDATA[abc..xyz]]>
            </line>
            <line>
              <![CDATA[Incorrect user ID or password]]>
            </line>
            <line>
              <![CDATA[admin..master]]>
            </line>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:driverFactory.DriverScript@50eac852]" started-at="2024-10-14T23:57:31 IST" name="tearDown" finished-at="2024-10-14T23:57:31 IST" duration-ms="618" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- driverFactory.DriverScript -->
    </test> <!-- login testcase -->
    <test started-at="2024-10-14T23:57:31 IST" name="Customer" finished-at="2024-10-14T23:59:00 IST" duration-ms="88236">
      <class name="driverFactory.AppTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:driverFactory.AppTest@79924b]" started-at="2024-10-14T23:57:32 IST" name="setUp" finished-at="2024-10-14T23:57:45 IST" duration-ms="13701" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="startTest()[pri:0, instance:driverFactory.AppTest@79924b]" started-at="2024-10-14T23:57:45 IST" name="startTest" finished-at="2024-10-14T23:58:59 IST" duration-ms="73384" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "org.apache.poi.xssf.usermodel.XSSFCell.getCellType()" because the return value of "org.apache.poi.xssf.usermodel.XSSFRow.getCell(int)" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.poi.xssf.usermodel.XSSFCell.getCellType()" because the return value of "org.apache.poi.xssf.usermodel.XSSFRow.getCell(int)" is null
at utilities.ExcelFileUtil.getDataFromCell(ExcelFileUtil.java:35)
at driverFactory.AppTest.startTest(AppTest.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[Customer added sucessfullyCustomer-00000011567........Customer-00000011567]]>
            </line>
            <line>
              <![CDATA[Customer added sucessfullyCustomer-00000011568........Customer-00000011568]]>
            </line>
            <line>
              <![CDATA[customer is not addedCustomer-00000011569.......Customer-00000007928]]>
            </line>
            <line>
              <![CDATA[Customer added sucessfullyCustomer-00000011570........Customer-00000011570]]>
            </line>
            <line>
              <![CDATA[Customer added sucessfullyCustomer-00000011571........Customer-00000011571]]>
            </line>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:driverFactory.AppTest@79924b]" started-at="2024-10-14T23:58:59 IST" name="tearDown" finished-at="2024-10-14T23:59:00 IST" duration-ms="1137" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- driverFactory.AppTest -->
    </test> <!-- Customer -->
  </suite> <!-- Suite -->
</testng-results>
